# Generated by Django 4.2.2 on 2023-06-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="movie",
        ),
        migrations.AddField(
            model_name="list",
            name="movies",
            field=models.ManyToManyField(to="api.movie"),
        ),
    ]
