# Generated by Django 4.2.2 on 2023-06-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_list_movie_list_movies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="list",
        ),
        migrations.AddField(
            model_name="user",
            name="lists",
            field=models.ManyToManyField(related_name="users", to="api.list"),
        ),
    ]
