# Generated by Django 4.2.2 on 2023-06-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_user_is_active_user_is_staff_user_last_login_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.CharField(max_length=1000),
        ),
    ]
