# Generated by Django 4.2.2 on 2023-06-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_user_last_login_alter_user_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="secure_password",
            field=models.CharField(default="", max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
