# Generated by Django 4.2.2 on 2023-06-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_secure_password_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="secure_password",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
